# Auto-switch the default output to Bluetooth sinks when they connect
wireplumber.components = [
  {
    name = bt-switch-on-connect.lua, type = script/lua
    provides = hooks.user.bt-switch-on-connect
  }
]

wireplumber.profiles = {
  main = {
    hooks.user.bt-switch-on-connect = required
  }
}