excluded_paths:
    mail-attachments:
        - /Users/raphael/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/66896932-6270-4751-B91F-7169D222B1AE
    old-downloads:
        - /Users/raphael/Downloads/8200 academy - web CTF - 5
    teams-new:
        - /Users/raphael/Library/Group Containers/UBF8T346G9.com.microsoft.teams/.com.apple.containermanagerd.metadata.plist
        - /Users/raphael/Library/Group Containers/UBF8T346G9.com.microsoft.teams/Library
