local M = {}

M.palette = {
    base = "#303446",
    text = "#c6d0f5",
    rosewater = "#f2d5cf",
    flamingo = "#eebebe",
    pink = "#f4b8e4",
    peach = "#ef9f76",
    yellow = "#e5c890",
    teal = "#81c8be",
    blue = "#8caaee",
    green = "#a6d189",
    red = "#e78284",
    mauve = "#ca9ee6",
    sky = "#99d1db",
    sapphire = "#85c1dc",
    surface0 = "#292c3c",
    surface1 = "#414559",
    surface2 = "#51576d",
    overlay0 = "#51576d",
    subtext0 = "#838ba7",
    comment = "#7a6e80",
    operator = "#e89292",
    punctuation = "#8a7e90",
    keyword_purple = "#c8a0e0",
    constant = "#efad8a",
    linenr = "#9a8ea0",
    storage = "#d4a0e8",
    select_bg = "#5a5060",
    select_fg = "#d4c5d5",
    dark_text = "#5C3A21",
    rust = "#EFC0C0",
}

local p = M.palette

local rust_groups = {
    "@function",
    "@function.call",
    "@function.builtin",
    "@function.macro",
    "@lsp.type.function",
    "@lsp.typemod.function.declaration",
    "@lsp.typemod.function.defaultLibrary",
    "@lsp.typemod.function.readonly",
}

M.lualine = {
    normal = {
        a = { bg = p.flamingo, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.flamingo },
        c = { bg = "NONE", fg = p.pink },
    },
    insert = {
        a = { bg = p.rosewater, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.rosewater },
        c = { bg = "NONE", fg = p.flamingo },
    },
    visual = {
        a = { bg = p.pink, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.pink },
        c = { bg = "NONE", fg = p.flamingo },
    },
    replace = {
        a = { bg = p.red, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.red },
        c = { bg = "NONE", fg = p.flamingo },
    },
    command = {
        a = { bg = p.peach, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.peach },
        c = { bg = "NONE", fg = p.flamingo },
    },
    terminal = {
        a = { bg = p.pink, fg = p.base, gui = "bold" },
        b = { bg = p.surface0, fg = p.pink },
        c = { bg = "NONE", fg = p.flamingo },
    },
    inactive = {
        a = { bg = "NONE", fg = p.flamingo },
        b = { bg = "NONE", fg = p.surface1, gui = "bold" },
        c = { bg = "NONE", fg = p.overlay0 },
    },
}

M.groups = {
    -- Base UI
    Normal = { fg = p.text, bg = "NONE" },
    NormalFloat = { fg = p.text, bg = "NONE" },
    NormalSB = { fg = p.text, bg = "NONE" },
    FloatBorder = { fg = p.select_fg, bg = "NONE" },
    FloatTitle = { fg = p.base, bg = "#F0C1C1" },
    CursorLine = { bg = "NONE" },
    CursorLineNr = { fg = p.pink },
    CursorColumn = { bg = "NONE" },
    LineNr = { fg = p.linenr },
    SignColumn = { bg = "NONE" },
    FoldColumn = { bg = "NONE" },
    Folded = { fg = p.subtext0, bg = "NONE" },
    StatusLine = { fg = p.text, bg = "NONE" },
    StatusLineNC = { fg = p.overlay0, bg = "NONE" },
    WinBar = { fg = p.subtext0 },
    WinBarNC = { fg = p.overlay0 },
    WinSeparator = { fg = p.overlay0 },
    VertSplit = { fg = p.overlay0 },
    TabLine = { fg = p.overlay0, bg = "NONE" },
    TabLineSel = { fg = p.pink, bg = "NONE" },
    TabLineFill = { bg = "NONE" },
    Pmenu = { fg = p.text, bg = "NONE" },
    PmenuSel = { fg = p.pink, bg = "NONE" },
    PmenuKind = { fg = p.rosewater, bg = "NONE" },
    PmenuKindSel = { fg = p.pink, bg = "NONE" },
    PmenuExtra = { fg = p.subtext0, bg = "NONE" },
    PmenuExtraSel = { fg = p.text, bg = "NONE" },
    PmenuSbar = { bg = "NONE" },
    PmenuThumb = { bg = p.surface1 },
    Search = { bg = p.select_bg, fg = p.pink },
    IncSearch = { bg = p.flamingo, fg = p.dark_text },
    CurSearch = { bg = p.pink, fg = p.dark_text },
    Substitute = { bg = p.constant, fg = p.dark_text },
    Visual = { bg = p.select_bg, fg = p.select_fg },
    VisualNOS = { bg = p.select_bg },
    MatchParen = { fg = p.pink, bold = true },
    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.yellow },
    MsgArea = { fg = p.text },
    ModeMsg = { fg = p.pink, bold = true },
    Question = { fg = p.rosewater },
    MoreMsg = { fg = p.green },
    Title = { fg = p.pink, bold = true },
    Directory = { fg = p.teal },
    Conceal = { fg = p.overlay0 },
    ColorColumn = { bg = "NONE" },
    QuickFixLine = { bg = p.surface0 },
    WildMenu = { bg = p.surface1, fg = p.pink },
    Underlined = { fg = p.blue, underline = true },
    SpecialKey = { fg = p.teal },
    Whitespace = { fg = p.surface1 },
    EndOfBuffer = { fg = p.surface0 },
    NonText = { fg = p.surface1 },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.yellow, undercurl = true },
    SpellLocal = { sp = p.blue, undercurl = true },
    SpellRare = { sp = p.mauve, undercurl = true },
    Cursor = { bg = p.text, fg = p.base },
    lCursor = { bg = p.text, fg = p.base },

    -- Classic syntax
    Comment = { fg = "#949cbb", italic = true },
    Constant = { fg = p.constant },
    String = { fg = p.yellow },
    Character = { fg = p.yellow },
    Number = { fg = p.sky },
    Boolean = { fg = p.sky },
    Float = { fg = p.sky },
    Identifier = { fg = p.text },
    Function = { fg = p.pink },
    Statement = { fg = p.flamingo },
    Conditional = { fg = p.flamingo },
    Repeat = { fg = p.flamingo },
    Label = { fg = p.yellow },
    Operator = { fg = p.operator },
    Keyword = { fg = p.pink },
    Exception = { fg = p.operator },
    Include = { fg = p.operator },
    Define = { fg = p.flamingo },
    Macro = { fg = p.constant },
    PreCondit = { fg = p.constant },
    PreProc = { fg = p.flamingo },
    Special = { fg = p.rosewater },
    SpecialChar = { fg = p.rosewater },
    SpecialComment = { fg = p.subtext0 },
    Tag = { fg = p.pink },
    Delimiter = { fg = p.punctuation },
    Debug = { fg = p.operator },
    Type = { fg = p.keyword_purple },
    StorageClass = { fg = p.storage },
    Structure = { fg = p.storage },
    Typedef = { fg = p.storage },
    Todo = { bg = "#eebebe", fg = "#303446", bold = true },
    Error = { fg = p.red },
    MatchWord = { underline = true, sp = p.pink },

    -- Treesitter
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { bg = "#e78284", fg = "#303446" },
    ["@comment.warning"] = { bg = "#e5c890", fg = "#303446" },
    ["@comment.todo"] = { bg = "#eebebe", fg = "#303446" },
    ["@error"] = { fg = p.operator },
    ["@none"] = { fg = p.text },
    ["@string"] = { fg = p.yellow },
    ["@string.escape"] = { fg = p.rosewater },
    ["@string.regex"] = { fg = p.rosewater },
    ["@string.special"] = { fg = p.yellow },
    ["@string.special.symbol"] = { fg = p.yellow },
    ["@string.special.url"] = { fg = p.blue, underline = true },
    ["@character"] = { fg = p.yellow },
    ["@character.special"] = { fg = p.yellow },
    ["@number"] = { fg = p.sky },
    ["@boolean"] = { fg = p.sky },
    ["@float"] = { fg = p.sky },
    ["@constant"] = { fg = p.constant },
    ["@constant.builtin"] = { fg = p.constant },
    ["@constant.macro"] = { fg = p.constant },
    ["@module"] = { fg = p.text },
    ["@module.builtin"] = { fg = p.text },
    ["@variable"] = { fg = p.text },
    ["@variable.builtin"] = { fg = p.constant },
    ["@variable.member"] = { fg = p.rosewater },
    ["@variable.parameter"] = { fg = p.text },
    ["@property"] = { fg = p.rosewater },
    ["@field"] = { fg = p.rosewater },
    ["@function"] = { fg = p.pink },
    ["@function.builtin"] = { fg = p.pink },
    ["@function.call"] = { fg = p.pink },
    ["@function.macro"] = { fg = p.pink },
    ["@method"] = { fg = p.pink },
    ["@method.call"] = { fg = p.pink },
    ["@constructor"] = { fg = p.pink },
    ["@constructor.builtin"] = { fg = p.pink },
    ["@parameter"] = { fg = p.text },
    ["@parameter.reference"] = { fg = p.text },
    ["@keyword"] = { fg = p.keyword_purple },
    ["@keyword.conditional"] = { fg = p.keyword_purple },
    ["@keyword.repeat"] = { fg = p.keyword_purple },
    ["@keyword.function"] = { fg = p.flamingo },
    ["@keyword.return"] = { fg = p.flamingo },
    ["@keyword.operator"] = { fg = p.operator },
    ["@keyword.exception"] = { fg = p.keyword_purple },
    ["@keyword.import"] = { fg = p.keyword_purple },
    ["@keyword.directive"] = { fg = p.flamingo },
    ["@conditional"] = { fg = p.flamingo },
    ["@repeat"] = { fg = p.flamingo },
    ["@exception"] = { fg = p.operator },
    ["@include"] = { fg = p.operator },
    ["@label"] = { fg = p.yellow },
    ["@operator"] = { fg = p.operator },
    ["@type"] = { fg = p.peach },
    ["@type.builtin"] = { fg = p.peach },
    ["@type.qualifier"] = { fg = p.peach },
    ["@type.definition"] = { fg = p.peach },
    ["@storageclass"] = { fg = p.storage },
    ["@attribute"] = { fg = p.peach },
    ["@attribute.builtin"] = { fg = p.peach },
    ["@namespace"] = { fg = p.text },
    ["@punctuation"] = { fg = p.punctuation },
    ["@punctuation.delimiter"] = { fg = p.punctuation },
    ["@punctuation.bracket"] = { fg = p.punctuation },
    ["@punctuation.special"] = { fg = p.rosewater },
    ["@tag"] = { fg = p.pink },
    ["@tag.attribute"] = { fg = p.mauve },
    ["@tag.delimiter"] = { fg = p.punctuation },
    ["@markup.heading.1"] = { fg = p.pink },
    ["@markup.heading.2"] = { fg = p.rosewater },
    ["@markup.heading.3"] = { fg = p.yellow },
    ["@markup.heading.4"] = { fg = p.peach },
    ["@markup.heading.5"] = { fg = p.sky },
    ["@markup.heading.6"] = { fg = p.mauve },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.link"] = { fg = p.blue },
    ["@markup.link.url"] = { fg = p.blue, underline = true },
    ["@markup.list"] = { fg = p.text },
    ["@markup.quote"] = { fg = p.subtext0 },
    ["@markup.raw"] = { fg = p.text, bg = "NONE" },
    ["@markup.math"] = { fg = p.sky },
    ["@markup.environment"] = { fg = p.rosewater },
    ["@markup.emphasized"] = { italic = true },

    -- LSP
    ["@lsp.type.class"] = { fg = p.peach },
    ["@lsp.type.struct"] = { fg = p.peach },
    ["@lsp.type.enum"] = { fg = p.peach },
    ["@lsp.type.interface"] = { fg = p.peach },
    ["@lsp.type.type"] = { fg = p.peach },
    ["@lsp.type.typeParameter"] = { fg = p.peach },
    ["@lsp.type.parameter"] = { fg = p.text },
    ["@lsp.type.variable"] = { fg = p.text },
    ["@lsp.type.function"] = { fg = p.pink },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = p.constant },

    -- Diagnostics
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.teal },
    DiagnosticOk = { fg = p.green },
    DiagnosticUnnecessary = { fg = p.subtext0 },
    DiagnosticVirtualTextError = { fg = p.red },
    DiagnosticVirtualTextWarn = { fg = p.yellow },
    DiagnosticVirtualTextInfo = { fg = p.blue },
    DiagnosticVirtualTextHint = { fg = p.teal },
    DiagnosticUnderlineError = { undercurl = true, sp = "#ff5555" },
    DiagnosticUnderlineWarn = { undercurl = true, sp = "#ffb86c" },
    DiagnosticUnderlineInfo = { undercurl = true, sp = "#8be9fd" },
    DiagnosticUnderlineHint = { undercurl = true, sp = "#50fa7b" },
    DiagnosticSignError = { fg = p.red },
    DiagnosticSignWarn = { fg = p.yellow },
    DiagnosticSignInfo = { fg = p.blue },
    DiagnosticSignHint = { fg = p.teal },

    -- Git
    DiffAdd = { bg = "NONE", fg = p.green },
    DiffChange = { bg = "NONE", fg = p.yellow },
    DiffDelete = { bg = "NONE", fg = p.red },
    DiffText = { bg = "NONE", fg = p.blue },
    diffAdded = { fg = p.green },
    diffRemoved = { fg = p.red },
    GitSignsAdd = { fg = p.green },
    GitSignsAddLn = { fg = p.green },
    GitSignsAddNr = { fg = p.green },
    GitSignsChange = { fg = p.yellow },
    GitSignsChangeLn = { fg = p.yellow },
    GitSignsChangeNr = { fg = p.yellow },
    GitSignsDelete = { fg = p.red },
    GitSignsDeleteLn = { fg = p.red },
    GitSignsDeleteNr = { fg = p.red },

    -- Bufferline
    BufferLineFill = { bg = "NONE" },
    BufferLineBuffer = { fg = p.overlay0, bg = "NONE" },
    BufferLineBufferSelected = { fg = p.pink, bg = "NONE" },
    BufferLineBufferVisible = { fg = p.subtext0, bg = "NONE" },
    BufferLineIndicatorSelected = { fg = p.pink, bg = "NONE" },
    BufferLineIndicatorVisible = { fg = p.pink, bg = "NONE" },
    BufferLineSeparator = { bg = "NONE" },
    BufferLineSeparatorSelected = { bg = "NONE" },
    BufferLineSeparatorVisible = { bg = "NONE" },
    BufferLineCloseButton = { fg = p.overlay0, bg = "NONE" },
    BufferLineCloseButtonSelected = { fg = p.pink, bg = "NONE" },
    BufferLineCloseButtonVisible = { fg = p.subtext0, bg = "NONE" },
    BufferLineNumbers = { fg = p.overlay0, bg = "NONE" },
    BufferLineNumbersSelected = { fg = p.pink, bg = "NONE" },
    BufferLineNumbersVisible = { fg = p.subtext0, bg = "NONE" },
    BufferLineTab = { bg = "NONE" },
    BufferLineTabSelected = { fg = p.pink, bg = "NONE" },
    BufferLineTabClose = { fg = p.red, bg = "NONE" },
    BufferLineError = { fg = p.red, bg = "NONE" },
    BufferLineErrorSelected = { fg = p.red, bg = "NONE" },
    BufferLineWarning = { fg = p.yellow, bg = "NONE" },
    BufferLineWarningSelected = { fg = p.yellow, bg = "NONE" },
    BufferLineInfo = { fg = p.blue, bg = "NONE" },
    BufferLineInfoSelected = { fg = p.blue, bg = "NONE" },
    BufferLineHint = { fg = p.teal, bg = "NONE" },
    BufferLineHintSelected = { fg = p.teal, bg = "NONE" },
    BufferLineModified = { fg = p.pink, bg = "NONE" },
    BufferLineModifiedSelected = { fg = p.pink, bg = "NONE" },
    BufferLineModifiedVisible = { fg = p.pink, bg = "NONE" },
    BufferLineDuplicate = { fg = p.overlay0, bg = "NONE" },
    BufferLineDuplicateSelected = { fg = p.pink, bg = "NONE" },
    BufferLineDuplicateVisible = { fg = p.subtext0, bg = "NONE" },

    -- Blink CMP
    BlinkCmpMenu = { bg = "NONE" },
    BlinkCmpMenuBorder = { fg = p.select_fg, bg = "NONE" },
    BlinkCmpMenuSelection = { bg = "NONE", fg = p.pink },
    BlinkCmpDoc = { bg = "NONE" },
    BlinkCmpDocBorder = { fg = p.select_fg, bg = "NONE" },
    BlinkCmpDocSeparator = { fg = p.surface1 },
    BlinkCmpLabel = { fg = p.text },
    BlinkCmpLabelMatch = { fg = p.rosewater },
    BlinkCmpLabelDetail = { fg = p.subtext0 },
    BlinkCmpLabelDeprecated = { fg = p.overlay0 },
    BlinkCmpSignatureHelp = { bg = "NONE" },
    BlinkCmpSignatureHelpBorder = { fg = p.select_fg, bg = "NONE" },
    BlinkCmpGhostText = { fg = p.comment, italic = true },
    BlinkCmpKindText = { fg = p.pink },
    BlinkCmpKindFunction = { fg = p.pink },
    BlinkCmpKindMethod = { fg = p.pink },
    BlinkCmpKindConstructor = { fg = p.peach },
    BlinkCmpKindVariable = { fg = p.text },
    BlinkCmpKindField = { fg = p.rosewater },
    BlinkCmpKindProperty = { fg = p.rosewater },
    BlinkCmpKindClass = { fg = p.peach },
    BlinkCmpKindStruct = { fg = p.peach },
    BlinkCmpKindInterface = { fg = p.peach },
    BlinkCmpKindEnum = { fg = p.peach },
    BlinkCmpKindEnumMember = { fg = p.rosewater },
    BlinkCmpKindModule = { fg = p.text },
    BlinkCmpKindKeyword = { fg = p.keyword_purple },
    BlinkCmpKindConstant = { fg = p.constant },
    BlinkCmpKindTypeParameter = { fg = p.peach },
    BlinkCmpKindSnippet = { fg = p.mauve },
    BlinkCmpKindUnit = { fg = p.sky },
    BlinkCmpKindValue = { fg = p.sky },
    BlinkCmpKindOperator = { fg = p.operator },
    BlinkCmpKindReference = { fg = p.blue },
    BlinkCmpKindFile = { fg = p.teal },
    BlinkCmpKindFolder = { fg = p.teal },
    BlinkCmpKindColor = { fg = p.mauve },
    BlinkCmpKindEvent = { fg = p.sky },
    BlinkCmpKindType = { fg = p.peach },

    -- Telescope
    TelescopeNormal = { fg = p.text, bg = "NONE" },
    TelescopeBorder = { fg = p.select_fg, bg = "NONE" },
    TelescopePromptNormal = { bg = "NONE" },
    TelescopePromptBorder = { fg = p.pink, bg = "NONE" },
    TelescopeResultsNormal = { bg = "NONE" },
    TelescopeResultsBorder = { fg = p.select_fg, bg = "NONE" },
    TelescopePreviewNormal = { bg = "NONE" },
    TelescopePreviewBorder = { fg = p.select_fg, bg = "NONE" },
    TelescopeSelection = { bg = p.select_bg, fg = p.pink },
    TelescopeSelectionCaret = { fg = p.pink, bg = p.select_bg },
    TelescopeMatching = { fg = p.rosewater },
    TelescopeTitle = { fg = p.pink, bg = "NONE" },
    TelescopePromptTitle = { fg = p.base, bg = p.pink },
    TelescopePreviewTitle = { fg = p.base, bg = p.teal },
    TelescopeResultsTitle = { fg = p.base, bg = p.peach },
    TelescopePromptPrefix = { fg = p.pink },
    TelescopePromptCounter = { fg = p.subtext0 },

    -- WhichKey
    WhichKey = { fg = p.pink },
    WhichKeyGroup = { fg = p.yellow },
    WhichKeyDesc = { fg = p.text },
    WhichKeySeparator = { fg = p.surface1 },
    WhichKeyFloat = { bg = "NONE" },
    WhichKeyBorder = { fg = p.select_fg, bg = "NONE" },
    WhichKeyValue = { fg = p.rosewater },

    -- Noice
    NoiceNormal = { bg = "NONE" },
    NoiceBorder = { fg = p.select_fg, bg = "NONE" },
    NoiceCmdline = { fg = p.text, bg = "NONE" },
    NoiceCmdlineIcon = { fg = p.pink },
    NoiceCmdlinePrompt = { fg = p.pink },
    NoiceCmdlinePopupNormal = { bg = "NONE" },
    NoiceCmdlinePopupBorder = { fg = p.select_fg, bg = "NONE" },
    NoiceCompletionItem = { fg = p.text },
    NoiceCompletionItemKindFunction = { fg = p.pink },
    NoiceCompletionItemKindKeyword = { fg = p.keyword_purple },
    NoiceCompletionItemKindVariable = { fg = p.text },
    NoiceLspDiagnosticError = { fg = p.red },
    NoiceLspDiagnosticWarn = { fg = p.yellow },
    NoiceLspDiagnosticInfo = { fg = p.blue },
    NoiceLspDiagnosticHint = { fg = p.teal },
    NoiceMini = { bg = "NONE" },

    -- Notify
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder = { fg = p.yellow },
    NotifyINFOBorder = { fg = p.blue },
    NotifyDEBUGBorder = { fg = p.teal },
    NotifyTRACEBorder = { fg = p.mauve },
    NotifyERRORTitle = { fg = p.red },
    NotifyWARNTitle = { fg = p.yellow },
    NotifyINFOTitle = { fg = p.blue },
    NotifyDEBUGTitle = { fg = p.teal },
    NotifyTRACETitle = { fg = p.mauve },
    NotifyERRORBody = { fg = p.text },
    NotifyWARNBody = { fg = p.text },
    NotifyINFOBody = { fg = p.text },
    NotifyDEBUGBody = { fg = p.text },
    NotifyTRACEBody = { fg = p.text },
    NotifyBackground = { bg = "NONE" },

    -- Trouble
    TroubleText = { fg = p.text },
    TroubleCount = { fg = p.pink },
    TroubleLocation = { fg = p.subtext0 },
    TroubleFold = { fg = p.overlay0 },
    TroubleIndent = { fg = p.surface1 },
    TroubleSignError = { fg = p.red },
    TroubleSignWarn = { fg = p.yellow },
    TroubleSignInfo = { fg = p.blue },
    TroubleSignHint = { fg = p.teal },
    TroublePreview = { bg = "NONE" },

    -- Snacks
    SnacksNormal = { bg = "NONE" },
    SnacksNormalNC = { bg = "NONE" },
    SnacksBorder = { fg = p.select_fg, bg = "NONE" },
    SnacksTitle = { fg = p.base, bg = p.yellow },
    SnacksInputNormal = { bg = "NONE" },
    SnacksInputBorder = { fg = p.pink, bg = "NONE" },
    SnacksInputTitle = { fg = p.base, bg = p.pink },
    SnacksPickerNormal = { bg = "NONE" },
    SnacksPickerBorder = { fg = p.select_fg, bg = "NONE" },
    SnacksPickerPromptTitle = { fg = p.base, bg = p.pink },
    SnacksPickerPreviewTitle = { fg = p.base, bg = p.teal },
    SnacksPickerResultsTitle = { fg = p.base, bg = p.peach },
    SnacksPickerSelection = { bg = p.select_bg, fg = p.pink },
    SnacksPickerMatch = { fg = p.rosewater },
    SnacksIndent1 = { fg = p.surface1 },
    SnacksIndent2 = { fg = p.surface1 },
    SnacksIndent3 = { fg = p.surface1 },
    SnacksIndentChunk = { fg = p.pink },
    SnacksIndentScope = { fg = p.pink },
    SnacksDashboardHeader = { fg = p.pink },
    SnacksDashboardIcon = { fg = p.rosewater },
    SnacksDashboardKey = { fg = p.pink },
    SnacksDashboardDesc = { fg = p.text },
    SnacksDashboardFooter = { fg = p.subtext0 },
    SnacksDashboardNormal = { bg = "NONE" },
    SnacksNotifierBorder = { bg = "NONE" },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierWarn = { fg = p.yellow },
    SnacksNotifierInfo = { fg = p.blue },
    SnacksNotifierDebug = { fg = p.teal },
    SnacksNotifierTrace = { fg = p.mauve },
    SnacksNotifierTitle = { fg = p.pink },
    SnacksNotifierBody = { fg = p.text },

    -- Mini
    MiniIndentscopeSymbol = { fg = p.pink },
    MiniIndentscopePrefix = { bg = "NONE" },
    MiniCursorword = { bg = p.surface1 },
    MiniCursorwordCurrent = { bg = p.surface1 },
    MiniJump = { fg = p.base, bg = p.pink },
    MiniJump2dSpot = { fg = p.pink },
    MiniStarterHeader = { fg = p.pink },
    MiniStarterFooter = { fg = p.subtext0 },
    MiniStarterItemBullet = { fg = p.rosewater },
    MiniStarterItem = { fg = p.text },
    MiniStarterItemSelected = { fg = p.pink },

    -- Flash
    FlashLabel = { fg = "#EABBBB", bg = "NONE" },
    FlashMatch = { bg = p.select_bg, fg = "#8CAAEE" },
    FlashCursor = { fg = "NONE" },
    FlashBackdrop = { fg = p.overlay0 },
    FlashTreesitterLabel = { fg = "#EABBBB", bg = "NONE" },

    -- Dashboard
    DashboardHeader = { fg = p.pink },
    DashboardShortCut = { fg = p.pink },
    DashboardShortCutIcon = { fg = p.pink },
    DashboardCenter = { fg = p.rosewater },
    DashboardFooter = { fg = p.subtext0 },
    DashboardKey = { fg = p.pink },
    DashboardDesc = { fg = p.text },
    DashboardIcon = { fg = p.rosewater },
    DashboardProjectTitle = { fg = p.pink },
    DashboardProjectTitleIcon = { fg = p.rosewater },
    DashboardProjectIcon = { fg = p.pink },

    -- RenderMarkdown
    RenderMarkdownH1 = { fg = p.pink },
    RenderMarkdownH1Bg = { bg = "NONE" },
    RenderMarkdownH2 = { fg = p.rosewater },
    RenderMarkdownH2Bg = { bg = "NONE" },
    RenderMarkdownH3 = { fg = p.yellow },
    RenderMarkdownH3Bg = { bg = "NONE" },
    RenderMarkdownH4 = { fg = p.peach },
    RenderMarkdownH4Bg = { bg = "NONE" },
    RenderMarkdownH5 = { fg = p.sky },
    RenderMarkdownH5Bg = { bg = "NONE" },
    RenderMarkdownH6 = { fg = p.mauve },
    RenderMarkdownH6Bg = { bg = "NONE" },
    RenderMarkdownBullet = { fg = p.overlay0 },
    RenderMarkdownCode = { fg = p.text, bg = "NONE" },
    RenderMarkdownCodeInline = { fg = p.rosewater },
    RenderMarkdownCodeInlineBg = { bg = "NONE" },
    RenderMarkdownTableHead = { fg = p.pink },
    RenderMarkdownTableRow = { fg = p.text },
    RenderMarkdownLink = { fg = p.blue },
    RenderMarkdownLinkHint = { fg = p.subtext0 },
    RenderMarkdownCallout = { fg = p.subtext0 },
    RenderMarkdownCheckbox = { fg = p.pink },
    RenderMarkdownCheckboxOn = { fg = p.green },
    RenderMarkdownCheckboxOff = { fg = p.overlay0 },
    RenderMarkdownQuote = { fg = p.rosewater },
    RenderMarkdownQuoteHighlight = { bg = "NONE" },
    RenderMarkdownDash = { fg = p.overlay0 },

    -- TodoComments (catppuccin frappe render)
    TodoBgTODO = { bg = "#99d1db", fg = "#000000", bold = true },
    TodoBgFIX = { bg = "#e78284", fg = "#000000", bold = true },
    TodoBgHACK = { bg = "#e5c890", fg = "#000000", bold = true },
    TodoBgWARN = { bg = "#e5c890", fg = "#000000", bold = true },
    TodoBgPERF = { bg = "#eebebe", fg = "#000000", bold = true },
    TodoBgNOTE = { bg = "#81c8be", fg = "#000000", bold = true },
    TodoBgTEST = { bg = "#eebebe", fg = "#000000", bold = true },
    TodoFgTODO = { fg = "#99d1db" },
    TodoFgFIX = { fg = "#e78284" },
    TodoFgHACK = { fg = "#e5c890" },
    TodoFgWARN = { fg = "#e5c890" },
    TodoFgPERF = { fg = "#eebebe" },
    TodoFgNOTE = { fg = "#81c8be" },
    TodoFgTEST = { fg = "#eebebe" },
    TodoSignTODO = { fg = "#99d1db" },
    TodoSignFIX = { fg = "#e78284" },
    TodoSignHACK = { fg = "#e5c890" },
    TodoSignWARN = { fg = "#e5c890" },
    TodoSignPERF = { fg = "#eebebe" },
    TodoSignNOTE = { fg = "#81c8be" },
    TodoSignTEST = { fg = "#eebebe" },

    -- Misc plugins
    SupermavenSuggestion = { fg = p.subtext0, italic = true },
    LspReferenceText = { bg = p.surface1 },
    LspReferenceRead = { bg = p.surface1 },
    LspReferenceWrite = { bg = p.surface1 },
    LspInlayHint = { fg = p.subtext0 },
    LspSignatureActiveParameter = { fg = p.pink, underline = true },
    LspCodeLens = { fg = p.subtext0 },
    LspCodeLensSeparator = { fg = p.surface1 },
    LspInfoBorder = { fg = p.select_fg },
    DapUIVariable = { fg = p.text },
    DapUIScope = { fg = p.pink },
    DapUIType = { fg = p.peach },
    DapUIDecoration = { fg = p.rosewater },
    DapUIBreakpointsPath = { fg = p.blue },
    DapUIBreakpointsCurrentLine = { fg = p.yellow },
    DapUISource = { fg = p.mauve },
    DapUIFloatBorder = { fg = p.select_fg },
    DapUIWatchesEmpty = { fg = p.red },
}

local function apply_groups()
    for group, spec in pairs(M.groups) do
        vim.api.nvim_set_hl(0, group, spec)
    end
end

local function apply_rust()
    for _, group in ipairs(rust_groups) do
        vim.api.nvim_set_hl(0, group, { fg = p.rust })
    end
end

local registered = false

function M.load()
    vim.g.colors_name = "raphael"
    apply_groups()

    if not registered then
        registered = true
        vim.api.nvim_create_autocmd("ColorScheme", {
            callback = function()
                if vim.g.colors_name == "raphael" then
                    apply_groups()
                    if vim.bo.filetype == "rust" then
                        apply_rust()
                    end
                end
            end,
        })
        vim.api.nvim_create_autocmd("FileType", {
            pattern = "rust",
            callback = function()
                apply_rust()
            end,
        })
    end
end

return M
