-- Generated by HyprMod

-- Monitors
hl.monitor({
	output = "HDMI-A-1",
	disabled = false,
	mode = "1920x1080@60.00Hz",
	position = "-1920x-250",
	scale = 1,
	cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"))
hl.unbind("SUPER + W")
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("helium-browser"))
hl.unbind("SUPER + CTRL + V")
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard"))
