-- Generated by HyprMod

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "2560x1440@144.00Hz",
    position = "0x0",
    scale = 1.33,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1366x768@60.01Hz",
    position = "1920x750",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"))
hl.unbind("SUPER + W")
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("helium-browser"))
hl.unbind("SUPER + CTRL + V")
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard"))
