-- Generated by HyprMod

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"))
hl.unbind("SUPER + W")
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("firefox"))
hl.unbind("SUPER + V")
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard"))
