# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#171211

# Main text color
theme[main_fg]=#ebe0dd

# Title color for boxes
theme[title]=#ebe0dd

# Highlight color for keyboard shortcuts
theme[hi_fg]=#f9b7a1

# Background color of selected item in processes box
theme[selected_bg]=#241e1d

# Foreground color of selected item in processes box
theme[selected_fg]=#f9b7a1

# Color of inactive/disabled text
theme[inactive_fg]=#9f8d87

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#d8c687

# Background color of the percentage meters
theme[meter_bg]=#9f8d87

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#d8c687

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#ffaaa8
theme[mem_box]=#ffd8bc
theme[net_box]=#faab99
theme[proc_box]=#ffa2bd

# Box divider line and small boxes line color
theme[div_line]=#52443f

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#ffd8bc
theme[temp_mid]=#ffeee6
theme[temp_end]=#ff9884

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#ffdb94
theme[cpu_mid]=#f2b2f2
theme[cpu_end]=#ffbbc0

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#ffaaa8
theme[free_mid]=#ffbbc0
theme[free_end]=#ffa2bd

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#f2b2f2
theme[cached_mid]=#ffa2bd
theme[cached_end]=#ffbbc0

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#ffbfa7
theme[available_mid]=#faab99
theme[available_end]=#ff9884

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#ffd8bc
theme[used_mid]=#ffdb94
theme[used_end]=#e1df87

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#ffbfa7
theme[download_mid]=#faab99
theme[download_end]=#ff9884

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#ffd8bc
theme[upload_mid]=#ffdb94
theme[upload_end]=#e1df87

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#f2b2f2
theme[process_mid]=#ffbbc0
theme[process_end]=#ffaaa8
