# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0e0e12

# Main text color
theme[main_fg]=#e6e4f0

# Title color for boxes
theme[title]=#e6e4f0

# Highlight color for keyboard shortcuts
theme[hi_fg]=#c2c3ee

# Background color of selected item in processes box
theme[selected_bg]=#191920

# Foreground color of selected item in processes box
theme[selected_fg]=#c2c3ee

# Color of inactive/disabled text
theme[inactive_fg]=#75747f

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#fee3ff

# Background color of the percentage meters
theme[meter_bg]=#75747f

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#fee3ff

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#bcb9ff
theme[mem_box]=#c8e3ff
theme[net_box]=#c7b6ee
theme[proc_box]=#aeb8ff

# Box divider line and small boxes line color
theme[div_line]=#474750

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#c8e3ff
theme[temp_mid]=#ffecf3
theme[temp_end]=#bea6fe

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#d2e0ff
theme[cpu_mid]=#b5c5ff
theme[cpu_end]=#c5c9ff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#bcb9ff
theme[free_mid]=#c5c9ff
theme[free_end]=#aeb8ff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#b5c5ff
theme[cached_mid]=#aeb8ff
theme[cached_end]=#c5c9ff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#c7b6ee
theme[available_end]=#bea6fe

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#c8e3ff
theme[used_mid]=#d2e0ff
theme[used_end]=#cedaff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#c7b6ee
theme[download_end]=#bea6fe

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#c8e3ff
theme[upload_mid]=#d2e0ff
theme[upload_end]=#cedaff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#b5c5ff
theme[process_mid]=#c5c9ff
theme[process_end]=#bcb9ff
