# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#131315

# Main text color
theme[main_fg]=#e4e2e4

# Title color for boxes
theme[title]=#e4e2e4

# Highlight color for keyboard shortcuts
theme[hi_fg]=#bac6e5

# Background color of selected item in processes box
theme[selected_bg]=#1f1f21

# Foreground color of selected item in processes box
theme[selected_fg]=#bac6e5

# Color of inactive/disabled text
theme[inactive_fg]=#8f9098

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#debdd9

# Background color of the percentage meters
theme[meter_bg]=#8f9098

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#debdd9

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#acbeff
theme[mem_box]=#c4e4ff
theme[net_box]=#bab9f0
theme[proc_box]=#9bbdff

# Box divider line and small boxes line color
theme[div_line]=#45474d

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#c4e4ff
theme[temp_mid]=#d0f9f4
theme[temp_end]=#aaacff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#c9e2ff
theme[cpu_mid]=#a5c9ff
theme[cpu_end]=#b8ccff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#acbeff
theme[free_mid]=#b8ccff
theme[free_end]=#9bbdff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#a5c9ff
theme[cached_mid]=#9bbdff
theme[cached_end]=#b8ccff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#bab9f0
theme[available_end]=#aaacff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#c4e4ff
theme[used_mid]=#c9e2ff
theme[used_end]=#c4ddff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#bab9f0
theme[download_end]=#aaacff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#c4e4ff
theme[upload_mid]=#c9e2ff
theme[upload_end]=#c4ddff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#a5c9ff
theme[process_mid]=#b8ccff
theme[process_end]=#acbeff
