prSections:
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Needs My Review
      filters: is:open review-requested:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
notificationsSections:
    - title: All
      filters: ""
    - title: Created
      filters: reason:author
    - title: Participating
      filters: reason:participating
    - title: Mentioned
      filters: reason:mention
    - title: Review Requested
      filters: reason:review-requested
    - title: Assigned
      filters: reason:assign
    - title: Subscribed
      filters: reason:subscribed
    - title: Team Mentioned
      filters: reason:team-mention
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 0.45
        height: 0.6
        position: auto
    prsLimit: 20
    prApproveComment: LGTM
    issuesLimit: 20
    notificationsLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            labels:
                width: 22
                hidden: true
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings: {}
repoPaths: {}
theme:
    ui:
        sectionsShowCount: true
        table:
            showSeparator: true
            compact: false
    colors:
        text:
            primary: "#c6d0f5"
            secondary: "#838ba7"
            inverted: "#303446"
            faint: "#51576d"
            warning: "#e78284"
            success: "#a6d189"
            actor: "#ca9ee6"
        background:
            selected: "#5a5060"
        border:
            primary: "#f4b8e4"
            secondary: "#51576d"
            faint: "#292c3c"
        inline:
            icons:
                newcontributor: "#a6d189"
                contributor: "#8caaee"
                collaborator: "#ef9f76"
                member: "#ca9ee6"
                owner: "#f4b8e4"
                unknownrole: "#838ba7"
    icons:
        inline:
            newcontributor: "󰎔"
            contributor: ""
            collaborator: ""
            member: ""
            owner: ""
            unknownrole: "󰭙"
pager:
    diff: "delta --diff-highlight --side-by-side"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: true
